version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: getir-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: getir_db
    volumes:
      - db_data_pg:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: spring-app
    container_name: getir-spring-app
    restart: always
    ports:
      - "8090:8090"
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:

volumes:
  db_data_pg: